# Generated by Django 3.2.9 on 2021-11-18 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_snips', '0006_alter_snippet_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='favorited',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
