# Generated by Django 3.2.9 on 2021-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snips', '0003_alter_snippet_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='libraries',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
